# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import image_compare_api.models
import image_compare_api.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCompare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Selecione a imagem de\n                               exemplo da certidão, normalmente nos formatos\n                               jpg, png, gif, etc.', null=True, upload_to=image_compare_api.models.ImageCompare.get_upload_to_image, validators=[image_compare_api.validators.FileValidator(max_size=1048576)], verbose_name='Imagem')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'imagens',
                'verbose_name': 'imagem',
            },
        ),
    ]
