# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import image_compare_api.models
import image_compare_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('image_compare_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecompare',
            name='image',
            field=models.ImageField(help_text='Selecione a imagem de\n                               exemplo da certidão, normalmente nos formatos\n                               jpg, png, gif, etc.', upload_to=image_compare_api.models.ImageCompare.get_upload_to_image, validators=[image_compare_api.validators.FileValidator(max_size=1048576)], verbose_name='Imagem'),
        ),
    ]
